//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pizza", Namespace="http://schemas.datacontract.org/2004/07/HalloDataContracts")]
    public partial class Pizza : object
    {
        
        private System.Collections.Generic.List<string> BelägeField;
        
        private bool GeschnittenField;
        
        private int MyPropertyField;
        
        private decimal PreisField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Beläge
        {
            get
            {
                return this.BelägeField;
            }
            set
            {
                this.BelägeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Geschnitten
        {
            get
            {
                return this.GeschnittenField;
            }
            set
            {
                this.GeschnittenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MyProperty
        {
            get
            {
                return this.MyPropertyField;
            }
            set
            {
                this.MyPropertyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Preis
        {
            get
            {
                return this.PreisField;
            }
            set
            {
                this.PreisField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PizzaService.IPizzaService")]
    public interface IPizzaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/GetData", ReplyAction="http://tempuri.org/IPizzaService/GetDataResponse")]
        PizzaService.GetDataResponse GetData(PizzaService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/GetData", ReplyAction="http://tempuri.org/IPizzaService/GetDataResponse")]
        System.Threading.Tasks.Task<PizzaService.GetDataResponse> GetDataAsync(PizzaService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/BestellPizza", ReplyAction="http://tempuri.org/IPizzaService/BestellPizzaResponse")]
        PizzaService.BestellPizzaResponse BestellPizza(PizzaService.BestellPizzaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/BestellPizza", ReplyAction="http://tempuri.org/IPizzaService/BestellPizzaResponse")]
        System.Threading.Tasks.Task<PizzaService.BestellPizzaResponse> BestellPizzaAsync(PizzaService.BestellPizzaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest()
        {
        }
        
        public GetDataRequest(int value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDataResult;
        
        public GetDataResponse()
        {
        }
        
        public GetDataResponse(string GetDataResult)
        {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BestellPizza", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BestellPizzaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PizzaService.Pizza pizza;
        
        public BestellPizzaRequest()
        {
        }
        
        public BestellPizzaRequest(PizzaService.Pizza pizza)
        {
            this.pizza = pizza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BestellPizzaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BestellPizzaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PizzaService.Pizza BestellPizzaResult;
        
        public BestellPizzaResponse()
        {
        }
        
        public BestellPizzaResponse(PizzaService.Pizza BestellPizzaResult)
        {
            this.BestellPizzaResult = BestellPizzaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IPizzaServiceChannel : PizzaService.IPizzaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class PizzaServiceClient : System.ServiceModel.ClientBase<PizzaService.IPizzaService>, PizzaService.IPizzaService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PizzaServiceClient() : 
                base(PizzaServiceClient.GetDefaultBinding(), PizzaServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPizzaService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PizzaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PizzaServiceClient.GetBindingForEndpoint(endpointConfiguration), PizzaServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PizzaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PizzaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PizzaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PizzaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PizzaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PizzaService.GetDataResponse GetData(PizzaService.GetDataRequest request)
        {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<PizzaService.GetDataResponse> GetDataAsync(PizzaService.GetDataRequest request)
        {
            return base.Channel.GetDataAsync(request);
        }
        
        public PizzaService.BestellPizzaResponse BestellPizza(PizzaService.BestellPizzaRequest request)
        {
            return base.Channel.BestellPizza(request);
        }
        
        public System.Threading.Tasks.Task<PizzaService.BestellPizzaResponse> BestellPizzaAsync(PizzaService.BestellPizzaRequest request)
        {
            return base.Channel.BestellPizzaAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPizzaService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPizzaService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/HalloDataContracts/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PizzaServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPizzaService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PizzaServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPizzaService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPizzaService,
        }
    }
}
