//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pizza", Namespace="http://schemas.datacontract.org/2004/07/HalloDataContracts")]
    public partial class Pizza : object
    {
        
        private System.Collections.Generic.List<string> BelägeField;
        
        private bool GeschnittenField;
        
        private decimal PreisField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Beläge
        {
            get
            {
                return this.BelägeField;
            }
            set
            {
                this.BelägeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Geschnitten
        {
            get
            {
                return this.GeschnittenField;
            }
            set
            {
                this.GeschnittenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Preis
        {
            get
            {
                return this.PreisField;
            }
            set
            {
                this.PreisField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PizzaFehler", Namespace="http://schemas.datacontract.org/2004/07/HalloDataContracts")]
    public partial class PizzaFehler : object
    {
        
        private string MessageField;
        
        private ServiceReference1.Pizza PizzaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Pizza Pizza
        {
            get
            {
                return this.PizzaField;
            }
            set
            {
                this.PizzaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPizzaService")]
    public interface IPizzaService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/GetData", ReplyAction="http://tempuri.org/IPizzaService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/GetData", ReplyAction="http://tempuri.org/IPizzaService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/BestellPizza", ReplyAction="http://tempuri.org/IPizzaService/BestellPizzaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.PizzaFehler), Action="http://tempuri.org/IPizzaService/BestellPizzaPizzaFehlerFault", Name="PizzaFehler", Namespace="http://schemas.datacontract.org/2004/07/HalloDataContracts")]
        ServiceReference1.Pizza BestellPizza(ServiceReference1.Pizza pizza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaService/BestellPizza", ReplyAction="http://tempuri.org/IPizzaService/BestellPizzaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Pizza> BestellPizzaAsync(ServiceReference1.Pizza pizza);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IPizzaServiceChannel : ServiceReference1.IPizzaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class PizzaServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IPizzaService>, ServiceReference1.IPizzaService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PizzaServiceClient() : 
                base(PizzaServiceClient.GetDefaultBinding(), PizzaServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPizzaService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PizzaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PizzaServiceClient.GetBindingForEndpoint(endpointConfiguration), PizzaServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PizzaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PizzaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PizzaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PizzaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PizzaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public ServiceReference1.Pizza BestellPizza(ServiceReference1.Pizza pizza)
        {
            return base.Channel.BestellPizza(pizza);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Pizza> BestellPizzaAsync(ServiceReference1.Pizza pizza)
        {
            return base.Channel.BestellPizzaAsync(pizza);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPizzaService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPizzaService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/HalloDataContracts/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PizzaServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPizzaService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PizzaServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPizzaService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPizzaService,
        }
    }
}
